name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Type check
        run: npm run typecheck
      - name: Unit tests
        run: npm run test:unit
      - name: Integration tests
        run: npm run test:integration
      - name: Coverage
        run: npm run test:coverage
      - name: Build
        run: npm run build
      - name: Docker build
        run: docker build -t acp-commerce-mcp-server .
